[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sports = "CDf5QvcmJzaf4i6FSioCbMCayuPsStXDTPxNijMiE9Cq"

[programs.devnet]
sports = "CDf5QvcmJzaf4i6FSioCbMCayuPsStXDTPxNijMiE9Cq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/phantom-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
buy_team_test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/buy_team_test.ts"
simple_initialize_test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/simple_initialize_test.ts"
stake_team_test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/stake_team_test.ts"

[profile.release]
opt-level = "z"       # optimiza para tamaño
lto = true            # Link-Time Optimization
codegen-units = 1     # menos unidades de compilación mejora LTO
panic = "abort"       # elimina manejo de panic costoso
